"""empty message

Revision ID: 0bb54b7c0ab1
Revises: 938655de0859
Create Date: 2019-04-20 18:08:38.132542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb54b7c0ab1'
down_revision = '938655de0859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('instructions', sa.String(length=345), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'instructions')
    # ### end Alembic commands ###
